---
# https://taskfile.dev

version: '3'

tasks:

  python:
    desc: Install/Upgrade Ansible and Python packages
    cmds:
      # Upgrade pip3 and install wheel
      - pip3 install --upgrade pip wheel
      # Install/upgrade requirements
      - pip3 install --upgrade -r requirements.txt

  lint:
    desc: Lint with Molecule
    cmds:
      - molecule lint

  test:
    desc: Test roles with Molecule
    cmds:
      - molecule test

...
