---
# https://taskfile.dev

version: '3'

tasks:

  lint:
    desc: Lint with Molecule
    cmds:
      - molecule lint

  test:
    desc: Test roles with Molecule
    cmds:
      - molecule test

...
