---
# https://taskfile.dev

version: '3'

tasks:

  update:
    desc: Install/Update Ansible and Python packages
    cmds:
      - pip3 install --upgrade -r requirements.txt

  lint:
    desc: Lint with Molecule
    cmds:
      - molecule lint

  test:
    desc: Test roles with Molecule
    cmds:
      - molecule test

...
