---

- name: Setup RedHat
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Setup Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Install Docker
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: docker_restart_dockerd

- name: Ensure Docker is started and enabled at boot
  ansible.builtin.service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified
  ansible.builtin.meta: flush_handlers

- name: Install Docker compose
  ansible.builtin.include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- name: Add users to Docker group
  ansible.builtin.include_tasks: docker-users.yml
  when: docker_users | length > 0

...
