---

- name: Setup RedHat
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_facts["os_family"] == "RedHat"

- name: Setup Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_facts["os_family"] == "Debian"

- name: Install Docker
  become: true
  ansible.builtin.package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: docker_restart_dockerd

- name: Check if Docker daemon.json exists
  ansible.builtin.stat:
    path: "{{ docker_daemon_file }}"
  register: docker_daemon_stat_result

- name: Create Docker daemon.json
  become: true
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "{{ docker_daemon_file }}"
    mode: "0644"
  when: not docker_daemon_stat_result.stat.exists

- name: Ensure Docker logs send to journald
  become: true
  ansible.builtin.lineinfile:
    path: "{{ docker_daemon_file }}"
    regexp: '"log-driver": '
    insertbefore: '^}'
    line: '  "log-driver": "journald"'

- name: Ensure Docker is started and enabled at boot
  become: true
  ansible.builtin.service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified
  ansible.builtin.meta: flush_handlers

- name: Deploy docker-image-prune service
  become: true
  ansible.builtin.template:
    src: docker-image-prune.service.j2
    dest: /etc/systemd/system/docker-image-prune.service
    owner: root
    group: root
    mode: "0644"
  register: docker_image_prune_service

- name: Deploy docker-image-prune timer
  become: true
  ansible.builtin.template:
    src: docker-image-prune.timer.j2
    dest: /etc/systemd/system/docker-image-prune.timer
    owner: root
    group: root
    mode: "0644"
  register: docker_image_prune_timer

- name: Reload system
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: >-
    (docker_image_prune_service is defined and docker_image_prune_service.changed)
    or (docker_image_prune_timer is defined and docker_image_prune_timer.changed)

- name: Enable docker-image-prune.timer
  become: true
  ansible.builtin.systemd_service:
    name: podman-image-prune.timer
    enabled: true
    state: started

- name: Install Docker compose
  ansible.builtin.include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- name: Add users to Docker group
  ansible.builtin.include_tasks: docker-users.yml
  when: docker_users | length > 0

...
