---

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    # - verify
    # - destroy
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: debian:11
    # pre_build_image: true
  - name: ubuntu
    image: ubuntu:22.04
    # pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: testinfra

...
