---

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    # - verify
    # - destroy
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
# - name: debian
#   image: docker.io/geerlingguy/docker-debian11-ansible
#   command: /lib/systemd/systemd
#   pre_build_image: true
#   privileged: true
# - name: fedora
#   image: docker.io/geerlingguy/docker-fedora36-ansible
#   command: /lib/systemd/systemd
#   pre_build_image: true
#   privileged: true
# - name: centos
#   image: docker.io/geerlingguy/docker-centos8-ansible
#   command: /lib/systemd/systemd
#   pre_build_image: true
#   privileged: true
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible

...
