---

- name: Prepare Molecule
  hosts: all
  gather_facts: true

  tasks:
    - name: Update apt
      become: true
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

...
